# Azure DevOps pipeline configuration for MySQL database deployment and schema updates
trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  MYSQL_SERVER: "db-rcha5267.mysql.database.azure.com"
  MYSQL_DATABASE: "studentdb1"
  MYSQL_USERNAME: "rootdb@db-rcha5267"  # Include the server in the username
  MYSQL_PASSWORD: $(MYSQL_PASSWORD)  # Secure password stored in pipeline variables

steps:
  # Step 1: Install MySQL client tools
  - script: |
      apt-get update
      apt-get install -y mysql-client
    displayName: "Install MySQL client tools"

  # Step 2: Validate database connection
  - script: |
      mysql -h $(MYSQL_SERVER) -u $(MYSQL_USERNAME) -p$(MYSQL_PASSWORD) -e "SELECT 1;"
    displayName: "Validate MySQL database connection"

  # Step 3: Deploy `create_table.sql`
  - script: |
      mysql -h $(MYSQL_SERVER) -u $(MYSQL_USERNAME) -p$(MYSQL_PASSWORD) $(MYSQL_DATABASE) < create_table.sql
    displayName: "Deploy create_table.sql"

  # Step 4: Run `update_table.sql`
  - script: |
      mysql -h $(MYSQL_SERVER) -u $(MYSQL_USERNAME) -p$(MYSQL_PASSWORD) $(MYSQL_DATABASE) < update_table.sql
    displayName: "Run update_table.sql"

  # Step 5: Validate schema update
  - script: |
      mysql -h $(MYSQL_SERVER) -u $(MYSQL_USERNAME) -p$(MYSQL_PASSWORD) $(MYSQL_DATABASE) -e "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Students' AND COLUMN_NAME = 'Email';"
    displayName: "Validate schema update"
